# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import login_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrnm', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pwd', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to=login_app.models.user_directory_path)),
            ],
        ),
    ]
