# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-08 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_userprofileinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='usrnm',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
