# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0002_auto_20180208_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeable',
            name='Section',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
