# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0003_changeable_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeable',
            name='BinaryArray',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
