# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0004_changeable_binaryarray'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateMatrix', models.CharField(max_length=10000, null=True)),
                ('CompChooses', models.CharField(max_length=100, null=True)),
                ('CompMovesTo', models.CharField(max_length=100, null=True)),
                ('CompMadeMove', models.CharField(max_length=100, null=True)),
                ('Section', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
