# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0005_statedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Changeable',
        ),
    ]
