# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0006_delete_changeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='statedata',
            name='AttackingPLaces',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CheckMate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompDownInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompLeftInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompNEInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompNWInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompRightInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompSEInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompSWInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompUpInCheck',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='FreeMove',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='InCheckPLaces',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='SaveAttackingPLaces',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='SaveInCheckPLaces',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
