# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0007_auto_20180224_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statedata',
            name='AttackingPLaces',
        ),
        migrations.RemoveField(
            model_name='statedata',
            name='InCheckPLaces',
        ),
        migrations.RemoveField(
            model_name='statedata',
            name='SaveAttackingPLaces',
        ),
        migrations.RemoveField(
            model_name='statedata',
            name='SaveInCheckPLaces',
        ),
        migrations.AddField(
            model_name='statedata',
            name='CanSaveKing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CurrentDirectionArray',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='InGuard',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='PieceInGuard',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='SpaceLength',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
