# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0009_statedata_attackerarray'),
    ]

    operations = [
        migrations.AddField(
            model_name='statedata',
            name='Attackers',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='Savers',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
