# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0010_auto_20180309_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='statedata',
            name='KingHasMoved',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='PawnIDArray',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='Rook1HasMoved',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='Rook2HasMoved',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
