# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChessApp', '0013_statedata_removedpieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='statedata',
            name='CompCastleMadeMove',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='CompCastleSide',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
