# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_enthusiasts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='title',
        ),
        migrations.AddField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
