# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('put_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='putmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='putmodel',
            name='put_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
