# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-19 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('put_app', '0003_auto_20180819_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='put',
            old_name='name',
            new_name='my_name',
        ),
    ]
