# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-20 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import put_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('put_app', '0005_auto_20180820_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=put_app.models.profile_image_path),
        ),
    ]
