# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0002_currentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccount',
            name='current_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='is_verified',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
