# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0017_auto_20180330_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='get_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='get_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='get_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='get_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
