# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0023_auto_20180401_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
