# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_userprofileinfo_test_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='password',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='test_text',
            new_name='usrnm',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='username',
        ),
    ]
