# Generated by Django 2.1.4 on 2018-12-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(blank=True, default='dude', max_length=20, null=True),
        ),
    ]
