# Generated by Django 2.1.4 on 2018-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_userprofileinfo_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
