# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 19:35
from __future__ import unicode_literals

import catpageapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=catpageapp.models.profile_image_path)),
                ('cats', models.CharField(max_length=1000, null=True)),
                ('cat_comments', models.CharField(max_length=1000, null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('account_name', models.CharField(max_length=20, null=True)),
                ('get_id', models.CharField(max_length=10, null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
