# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0004_currentaccount_is_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaccount',
            name='is_set',
        ),
    ]
