# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0005_remove_currentaccount_is_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='get_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='section',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='cat_user',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='get_id',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='section',
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='get_id',
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='section',
        ),
        migrations.RemoveField(
            model_name='main',
            name='get_id',
        ),
        migrations.RemoveField(
            model_name='main',
            name='section',
        ),
    ]
