# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 15:57
from __future__ import unicode_literals

import catpageapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0010_auto_20180326_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='cat_pic',
            field=models.ImageField(blank=True, null=True, upload_to=catpageapp.models.cat_image_path),
        ),
    ]
