# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0013_cat_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='unique_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
