# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0014_auto_20180327_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='unique_id',
            new_name='cat_unique_id',
        ),
    ]
