# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0015_auto_20180330_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='cat_unique_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
