# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0016_main_cat_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='get_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
