# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0006_auto_20180326_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='get_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='get_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='get_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currentaccount',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='get_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
