# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0008_auto_20180326_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
