# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0018_auto_20180331_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cat_comments',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='cats',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='comments',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_comments',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='cat_comments',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='cats',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='currentaccount',
            name='comments',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='cat_comments',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='cats',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='comments',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='story',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
