# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0020_main_my_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='my_cat_id',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
