# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0022_auto_20180401_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cat_comments',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cats',
        ),
        migrations.RemoveField(
            model_name='account',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='cat_comments',
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='cats',
        ),
        migrations.RemoveField(
            model_name='currentaccount',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='main',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='main',
            name='cat_comments',
        ),
        migrations.RemoveField(
            model_name='main',
            name='cats',
        ),
        migrations.RemoveField(
            model_name='main',
            name='name',
        ),
        migrations.RemoveField(
            model_name='main',
            name='picture',
        ),
    ]
