# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpageapp', '0024_auto_20180401_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaccount',
            name='filename',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
