# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 16:16
from __future__ import unicode_literals

import CatApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=CatApp.models.profile_image_path)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('breed', models.CharField(max_length=20, null=True)),
                ('story', models.CharField(max_length=140, null=True)),
                ('cat_pic', models.ImageField(blank=True, null=True, upload_to=CatApp.models.cat_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Cat_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_comment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_pic', models.ImageField(blank=True, null=True, upload_to=CatApp.models.image_path)),
                ('comments', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CatApp.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat_Comment'),
        ),
        migrations.AddField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='cat_comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat_Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='cats',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat'),
        ),
        migrations.AddField(
            model_name='account',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CatApp.Comment'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
