# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-12 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='name',
            new_name='cat_name',
        ),
    ]
