# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0003_auto_20180314_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cat_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat_Comment'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat'),
        ),
        migrations.AlterField(
            model_name='account',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Comment'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat_Comment'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='main',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Account'),
        ),
        migrations.AlterField(
            model_name='main',
            name='cat_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat_Comment'),
        ),
        migrations.AlterField(
            model_name='main',
            name='cats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Cat'),
        ),
        migrations.AlterField(
            model_name='main',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.Comment'),
        ),
    ]
