# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0004_auto_20180315_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.User'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat_comments',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CatApp.User'),
        ),
    ]
