# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0008_auto_20180316_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='get_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='get_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='get_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
