# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0010_remove_cat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CatApp.User'),
        ),
    ]
