# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0011_cat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='account_user',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='user',
            new_name='cat_user',
        ),
    ]
