# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0012_auto_20180317_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_user',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='CatApp.User'),
        ),
    ]
