# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0014_auto_20180317_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='cat_user',
            field=models.IntegerField(default=1),
        ),
    ]
