# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0016_auto_20180318_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_user',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
