# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0017_auto_20180318_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
