# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp', '0018_auto_20180318_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
