# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-18 15:57
from __future__ import unicode_literals

import cat_enthusiasts_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20, null=True)),
                ('breed', models.CharField(max_length=30, null=True)),
                ('story', models.CharField(max_length=140, null=True)),
                ('cat_pic', models.ImageField(blank=True, null=True, upload_to=cat_enthusiasts_app.models.cat_image_path)),
                ('is_remove', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140, null=True)),
                ('is_remove', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=cat_enthusiasts_app.models.profile_image_path)),
                ('profile_name', models.CharField(max_length=15, null=True)),
                ('get_id', models.CharField(default='', max_length=10, null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_enthusiasts_app.Main')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_enthusiasts_app.Main'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_enthusiasts_app.Profile'),
        ),
        migrations.AddField(
            model_name='cat',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_enthusiasts_app.Main'),
        ),
        migrations.AddField(
            model_name='cat',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cat_enthusiasts_app.Profile'),
        ),
    ]
