# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_enthusiasts_app', '0002_auto_20180619_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='current_user',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='is_logged_in',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
