# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 08:46
from __future__ import unicode_literals

import CatApp3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_user', models.IntegerField(default=1, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=CatApp3.models.profile_image_path)),
                ('cats', models.CharField(max_length=1000, null=True)),
                ('cat_comments', models.CharField(max_length=1000, null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('account_name', models.CharField(max_length=20, null=True)),
                ('get_id', models.CharField(max_length=10, null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20, null=True)),
                ('breed', models.CharField(max_length=20, null=True)),
                ('story', models.CharField(max_length=140, null=True)),
                ('cat_pic', models.ImageField(blank=True, null=True, upload_to=CatApp3.models.cat_image_path)),
                ('cat_comments', models.CharField(max_length=1000, null=True)),
                ('cat_user', models.IntegerField(default=1, null=True)),
                ('get_id', models.CharField(max_length=10, null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_pic', models.ImageField(blank=True, null=True, upload_to=CatApp3.models.image_path)),
                ('cats', models.CharField(max_length=1000, null=True)),
                ('cat_comments', models.CharField(max_length=1000, null=True)),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('accounts', models.CharField(max_length=1000, null=True)),
                ('get_id', models.CharField(max_length=10, null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
