# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-20 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CatApp3', '0002_auto_20180320_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_user',
        ),
    ]
