# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PencilCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pencil', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('rubber', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('pen', models.CharField(blank=True, default='', max_length=15, null=True)),
            ],
        ),
    ]
