# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import image_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=10, null=True)),
                ('pic', models.ImageField(null=True, upload_to=image_app.models.image_path)),
            ],
        ),
    ]
